# -*- coding: utf-8 -*-
"""POTHOLE_DETECTION_YOLOV11-SEG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bL6dXDquD4wly501nXCW4wbinVn448N-
"""

import os
from google.colab import files

HOME = os.getcwd()
print(HOME)

!nvidia-smi

"""#INSTALL DEPENDENCIES"""

!pip install tqdm --upgrade
!pip install ultralytics roboflow supervision flash-attn torch

from IPython.display import Image, display
import glob
import random
import yaml
import shutil
import cv2
import torch
import ultralytics
from tqdm.notebook import tqdm
from ultralytics import YOLO

ultralytics.checks()

"""#IMPORTING DATASET FROM ROBOFLOW"""

from google.colab import userdata

from roboflow import Roboflow
rf = Roboflow(api_key=userdata.get('robo_api'))
project = rf.workspace("frysushiws").project("pothole_detection-yulbt")
version = project.version(1)
dataset = version.download("yolov11")

!sed -i '$d' {dataset.location}/data.yaml
!sed -i '$d' {dataset.location}/data.yaml
!sed -i '$d' {dataset.location}/data.yaml
!sed -i '$d' {dataset.location}/data.yaml
!echo -e "test: ../test/images\ntrain: ../train/images\nval: ../valid/images" >> {dataset.location}/data.yaml

"""#CUSTOM TRAINING"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

!yolo task=detect mode=train model=yolo11s-seg.pt data={dataset.location}/data.yaml epochs=10 imgsz=640 plots=True

"""#RESULT"""

!ls {HOME}/runs/segment/train3/

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/segment/train/confusion_matrix.png', width=600)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/segment/train/results.png', width=600)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

Image(filename = f'{HOME}/runs/segment/train/val_batch0_pred.jpg', width = 600)

"""##TESTING WITH VIDEO"""

from google.colab import files
uploaded = files.upload()

uploaded_file_name = list(uploaded.keys())[0]
file_path = os.path.join(os.getcwd(), uploaded_file_name)

!pip install moviepy

from moviepy.editor import VideoFileClip

clip = VideoFileClip(uploaded_file_name)
clip_resized = clip.resize(width=640)
clip_resized.write_videofile("video_resized.mp4")

model = YOLO('/content/runs/segment/train/weights/best.pt')

results = model("video_resized.mp4", save=True, project='output', name='deteksi_video')

!apt install ffmpeg
!ffmpeg -i output/deteksi_video2/video_resized.avi -vcodec libx264 output/deteksi_video2/video_resized.mp4

from IPython.display import Video

Video("output/deteksi_video2/video_resized.mp4", embed=True)

"""#DEPLOY TO ROBOFLOW"""

rf = Roboflow(userdata.get('robo_api'))
workspace = rf.workspace("frysushiws")

workspace.deploy_model(
  model_type="yolov11",
  model_path="./runs/segment/train/",
  project_ids=["pothole_detection-yulbt"],
  model_name="pothole-segmentation-yolov11-v2"
)

"""#FINISH!

Reference:

---


Linas Kondrackis. (Oct 3, 2024). How to Train YOLOv11 Instance Segmentation on a Custom Dataset. Roboflow Blog: https://blog.roboflow.com/train-yolov11-instance-segmentation/
"""